name: Bug report
description: Report something that is broken or incorrect.
title: "[Bug]: "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight checklist
      options:
        - label: I searched existing issues and couldn’t find a duplicate.
          required: true
        - label: I’m using a supported/maintained version (or I can reproduce on latest).
          required: true
        - label: I can reproduce this issue consistently.
          required: false

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug clearly.
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      placeholder: Describe what you expected instead.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide steps so we can reproduce it.
      placeholder: |
        1. Go to '...'
        2. Run '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / error output
      description: Paste any relevant logs or stack traces. (Redact secrets!)
      render: shell
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Anything else that helps? Screenshots, links, regression info, etc.
    validations:
      required: false
