name: Feature request
description: Suggest an improvement or a new feature.
title: "[Feature]: "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion! Please be as concrete as possible.
        If this is a **question** or you need help using the project, consider starting a Discussion (if enabled).

  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight checklist
      options:
        - label: I searched existing issues and couldn’t find a duplicate.
          required: true
        - label: This is not a security report.
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
      placeholder: I’m frustrated when...
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to happen?
      placeholder: It would be great if...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches you considered and why they’re not ideal.
    validations:
      required: false

  - type: textarea
    id: scope
    attributes:
      label: Scope / details
      description: Any details that clarify requirements, edge cases, API shape, UX, etc.
    validations:
      required: false

  - type: dropdown
    id: willingness
    attributes:
      label: Are you willing to contribute a PR?
      options:
        - "Yes"
        - "Maybe"
        - "No"
    validations:
      required: true
